<<<<<<< HEAD
version: '3.6'

volumes:
  dbdata:

services:
  db:
    image: postgres:13.5-alpine
    restart: always
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=data_collector
=======
version: '3.3'

services:
  pg:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ukraine
      POSTGRES_USER: ukraine
    ports:
      - 5432:5432
  app:
    build:
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: pg
      DB_DATABASE: ukraine
      DB_USERNAME: ukraine
      DB_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - pg
>>>>>>> b10699dc814081e0da7c8295ecdf8bce6674b3da
