version: '3.3'

services:
  pg:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ukraine
      POSTGRES_USER: ukraine
    ports:
      - 5432:5432

  app:
    build:
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: pg
      DB_DATABASE: ukraine
      DB_USERNAME: ukraine
      DB_PASSWORD: password
    ports:
<<<<<<< HEAD
      - 8080:8080
=======
      - 8080:8080
  
  rubocop:
    extends:
      service: app
    command: bundle exec rubocop
>>>>>>> b388508fad2cf547fdc3a6f44069cc31d01534be
