version: '3.3'

services:
  pg:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ukraine
      POSTGRES_USER: ukraine
    ports:
      - 5432:5432

  app:
    build:
      dockerfile: Dockerfile-dev
      context: .
    depends_on:
      - pg
      - redis
      - sidekiq
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: pg
      DB_DATABASE: ukraine
      DB_USERNAME: ukraine
      DB_PASSWORD: password
      VCAP_SERVICES: '{"redis":[{"instance_name":"ukraine-sponsor-resettlement-development-redis", "credentials":{"uri":"redis://redis"}}]}'
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: password
    ports:
      - 8080:8080

  test:
    build:
      dockerfile: Dockerfile-dev
      context: .
    depends_on:
      - pg
      - redis
    volumes:
      - .:/app
    environment:
      RAILS_ENV: test
      DB_HOST: pg
      DB_USERNAME: ukraine
      DB_DATABASE: ukraine_test
      DB_PASSWORD: password
      VCAP_SERVICES: '{"redis":[{"instance_name":"ukraine-sponsor-resettlement-test-redis", "credentials":{"uri":"redis://redis"}}]}'
      REMOTE_API_URL: http://mock-api:8081/data
      INDIVIDUAL_CONFIRMATION_TEMPLATE_ID: "6c80930d-e25a-4dc6-8383-bb83a2c18d19"
      ORGANISATION_CONFIRMATION_TEMPLATE_ID: "3ae2501f-e2be-4ad6-886b-fcf5aa71d448"
      GOVUK_NOTIFY_API_KEY: ${GOVUK_NOTIFY_API_KEY}
    command: bin/test.sh

  sidekiq:
    build:
      dockerfile: Dockerfile-dev
      context: .
    depends_on:
      - pg
      - redis
      - mock-api
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: pg
      DB_DATABASE: ukraine
      DB_USERNAME: ukraine
      DB_PASSWORD: password
      VCAP_SERVICES: '{"redis":[{"instance_name":"ukraine-sponsor-resettlement-development-redis", "credentials":{"uri":"redis://redis"}}]}'
      REMOTE_API_URL: http://mock-api:8081/data
      INDIVIDUAL_CONFIRMATION_TEMPLATE_ID: "6c80930d-e25a-4dc6-8383-bb83a2c18d19"
      ORGANISATION_CONFIRMATION_TEMPLATE_ID: "3ae2501f-e2be-4ad6-886b-fcf5aa71d448"
      GOVUK_NOTIFY_API_KEY: ${GOVUK_NOTIFY_API_KEY}
    command: bundle exec sidekiq

  redis:
    image: redis

  mock-api:
    build:
      dockerfile: Dockerfile
      context: http-mock-server
    ports:
      - 8081:8081
