version: '3.3'

services:
  pg:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ukraine
      POSTGRES_USER: ukraine
    ports:
      - 5432:5432

  app:
    build:
      dockerfile: Dockerfile-dev
      context: .
    depends_on:
      - pg
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: pg
      DB_DATABASE: ukraine
      DB_USERNAME: ukraine
      DB_PASSWORD: password
      VCAP_SERVICES: '{"redis":[{"instance_name":"ukraine-sponsor-resettlement-development-redis", "credentials":{"uri":"redis://redis"}}]}'
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: password
    ports:
      - 8080:8080

  redis:
    image: redis
